fragment BlogParts on Blog {
  __typename
  title
  excerpt
  publishedAt
  image
  tags
  body
}

fragment EventsParts on Events {
  __typename
  title
  description
  date
  location
  image
  body
}

fragment NewsParts on News {
  __typename
  title
  excerpt
  publishedAt
  author
  image
  category
  body
}
