[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  command = "pnpm install --no-frozen-lockfile && npm run build"

[context.deploy-preview]
  command = "pnpm install --no-frozen-lockfile && npm run build"

[context.branch-deploy]
  command = "pnpm install --no-frozen-lockfile && npm run build"